/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yifwang' at '17-12-8 下午3:14' with Gradle 2.14.1
 *
 * @author yifwang, @date 17-12-8 下午3:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
